worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;

        # Serve static files (JS, CSS, images)
        location /static/ {
            alias   /Blogger/static/;  # Updated path inside Docker container
        }

        # Serve HTML templates
        location /templates/ {
            alias   /Blogger/templates/;  # Updated path inside Docker container
        }

        # API requests to FastAPI backend
        location / {
            proxy_pass http://127.0.0.1:8000;  # Forward API requests to Uvicorn
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Serve the main HTML page
        location / {
            root   /Blogger/templates;  # Updated path inside Docker container
            index  home.html;
            try_files $uri $uri/ =404;
        }

        # Custom error page for server errors
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /Blogger/templates;  # Updated path inside Docker container
        }
    }
}
